package me.skepi.skepifb.leaderboard;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.UUID;

public class LeaderboardManager {

    public static final int MAX_POSITIONS = 10;

    /**
     * Result of an add-entry attempt, used purely for admin-facing messaging - the caller decides
     * exactly what to say for each case.
     */
    public enum AddResult {
        ADDED,
        UPDATED,
        NOT_QUALIFIED,
        INVALID
    }

    private final JavaPlugin plugin;
    private final File leaderboardFile;
    private FileConfiguration configuration;

    public LeaderboardManager(JavaPlugin plugin) {
        this.plugin = plugin;
        File dataFolder = plugin.getDataFolder();
        if (!dataFolder.exists()) {
            dataFolder.mkdirs();
        }
        this.leaderboardFile = new File(dataFolder, "leaderboard.yml");
        createDefaultLeaderboardFileIfMissing();
        this.configuration = YamlConfiguration.loadConfiguration(leaderboardFile);
        createDefaultPositionTagsSectionIfMissing();
    }

    private void createDefaultLeaderboardFileIfMissing() {
        if (leaderboardFile.exists()) {
            return;
        }
        String defaultContent = "leaderboards: {}\n";
        try {
            Files.write(leaderboardFile.toPath(), defaultContent.getBytes(StandardCharsets.UTF_8));
        } catch (IOException ex) {
            plugin.getLogger().warning("Unable to create default leaderboard.yml: " + ex.getMessage());
        }
    }

    /**
     * Simple in-memory representation of one occupied leaderboard slot, used while re-sorting.
     */
    private static final class Entry {
        final UUID playerUuid;
        final String playerName;
        final double score;

        Entry(UUID playerUuid, String playerName, double score) {
            this.playerUuid = playerUuid;
            this.playerName = playerName;
            this.score = score;
        }
    }

    /**
     * Ensures the given mode has a leaderboard section to write into. Modes are not pre-registered
     * anywhere else - any arena/mode name works the first time an entry is added to it, which is
     * what lets a leaderboard exist "for every FastBuilder mode" without a separate creation step.
     */
    private void ensureLeaderboardSection(String normalizedMode, String displayName) {
        if (!configuration.isConfigurationSection("leaderboards." + normalizedMode)) {
            configuration.set("leaderboards." + normalizedMode + ".name", displayName == null ? normalizedMode : displayName);
        }
        ensurePositionTagsAutoGenerated(normalizedMode, displayName);
    }

    /**
     * Auto-generates a default positionTags entry for every position (1..MAX_POSITIONS) on this
     * mode, the first time anyone appears on its leaderboard - so an admin never has to hand-write
     * "dune.1" through "dune.10" just to make placements on a new mode taggable. Only fills in
     * positions that don't already have a mapping, so any manual customization (renamed display
     * text) is never overwritten by this.
     */
    private void ensurePositionTagsAutoGenerated(String normalizedMode, String displayName) {
        String label = (displayName == null || displayName.isBlank()) ? normalizedMode : displayName.trim();
        boolean changedAny = false;
        for (int position = 1; position <= MAX_POSITIONS; position++) {
            String base = "positionTags." + normalizedMode + "." + position;
            if (configuration.isConfigurationSection(base)) {
                continue;
            }
            configuration.set(base + ".display", "&b#" + position + " " + capitalize(label));
            changedAny = true;
        }
        if (changedAny) {
            save();
        }
    }

    private String capitalize(String text) {
        if (text == null || text.isEmpty()) {
            return text;
        }
        return Character.toUpperCase(text.charAt(0)) + text.substring(1);
    }

    public boolean leaderboardExists(String mode) {
        if (mode == null || mode.isBlank()) {
            return false;
        }
        return configuration.isConfigurationSection("leaderboards." + normalizeMode(mode));
    }

    public Set<String> getLeaderboards() {
        ConfigurationSection leaderboardsSection = configuration.getConfigurationSection("leaderboards");
        Set<String> modes = new LinkedHashSet<>();
        if (leaderboardsSection == null) {
            return modes;
        }
        for (String mode : leaderboardsSection.getKeys(false)) {
            modes.add(mode);
        }
        return modes;
    }

    public String getLeaderboardDisplayName(String mode) {
        if (mode == null || mode.isBlank()) {
            return "";
        }
        String normalizedMode = normalizeMode(mode);
        return configuration.getString("leaderboards." + normalizedMode + ".name", mode.trim());
    }

    /**
     * Reads every currently-occupied slot for a mode into a mutable, sortable list. Empty slots are
     * simply absent from this list - callers re-derive placeholder slots separately when rendering.
     */
    private List<Entry> readEntries(String normalizedMode) {
        List<Entry> entries = new ArrayList<>();
        if (!leaderboardExists(normalizedMode)) {
            return entries;
        }
        for (int position = 1; position <= MAX_POSITIONS; position++) {
            ConfigurationSection positionSection = configuration.getConfigurationSection("leaderboards." + normalizedMode + ".positions." + position);
            if (positionSection == null) {
                continue;
            }
            String player = positionSection.getString("player", null);
            if (player == null || player.isBlank()) {
                continue;
            }
            String uuidText = positionSection.getString("playerUuid", null);
            UUID uuid = null;
            if (uuidText != null) {
                try {
                    uuid = UUID.fromString(uuidText);
                } catch (IllegalArgumentException ignored) {
                }
            }
            double score = positionSection.getDouble("score", 0.0d);
            entries.add(new Entry(uuid, player, score));
        }
        return entries;
    }

    /**
     * Rewrites positions 1-10 from a (already sorted, already truncated) entry list, clearing
     * anything past the given list's size back to empty placeholders.
     */
    private void writeEntries(String normalizedMode, List<Entry> sortedEntries) {
        for (int i = 0; i < MAX_POSITIONS; i++) {
            int position = i + 1;
            String base = "leaderboards." + normalizedMode + ".positions." + position;
            if (i < sortedEntries.size()) {
                Entry entry = sortedEntries.get(i);
                configuration.set(base + ".player", entry.playerName);
                configuration.set(base + ".playerUuid", entry.playerUuid == null ? null : entry.playerUuid.toString());
                configuration.set(base + ".score", entry.score);
            } else {
                configuration.set(base + ".player", null);
                configuration.set(base + ".playerUuid", null);
                configuration.set(base + ".score", 0.0d);
            }
        }
        save();
    }

    /**
     * Adds (or updates, if the player already has a slot on this leaderboard) an entry with the
     * given time, keeping the board sorted fastest-first and capped at MAX_POSITIONS. If the board
     * is already full and this time does not beat the current slowest entry, nothing is written and
     * NOT_QUALIFIED is returned so the caller can tell the admin why nothing happened.
     */
    public AddResult addEntry(String mode, UUID playerUuid, String playerName, double time) {
        if (mode == null || mode.isBlank() || playerName == null || playerName.isBlank() || time < 0 || Double.isNaN(time) || Double.isInfinite(time)) {
            return AddResult.INVALID;
        }
        String normalizedMode = normalizeMode(mode);
        ensureLeaderboardSection(normalizedMode, mode.trim());

        List<Entry> entries = readEntries(normalizedMode);
        boolean isUpdate = false;

        // A player only ever occupies one slot on a given mode's leaderboard - adding again just
        // replaces their previous time rather than creating a second entry for the same person.
        for (int i = 0; i < entries.size(); i++) {
            Entry existing = entries.get(i);
            boolean samePlayer = (playerUuid != null && playerUuid.equals(existing.playerUuid))
                    || (playerUuid == null && existing.playerUuid == null && playerName.equalsIgnoreCase(existing.playerName));
            if (samePlayer) {
                entries.remove(i);
                isUpdate = true;
                break;
            }
        }

        if (!isUpdate && entries.size() >= MAX_POSITIONS) {
            double slowestCurrent = entries.stream().mapToDouble(e -> e.score).max().orElse(Double.MAX_VALUE);
            if (time >= slowestCurrent) {
                return AddResult.NOT_QUALIFIED;
            }
        }

        entries.add(new Entry(playerUuid, playerName, time));
        entries.sort(Comparator.comparingDouble(e -> e.score));
        if (entries.size() > MAX_POSITIONS) {
            entries = new ArrayList<>(entries.subList(0, MAX_POSITIONS));
        }
        writeEntries(normalizedMode, entries);
        return isUpdate ? AddResult.UPDATED : AddResult.ADDED;
    }

    /**
     * Removes the given player's entry from a mode's leaderboard, if present, and compacts the
     * remaining entries so there is no gap in the middle of the list. The time parameter is used to
     * confirm the correct entry is being removed (protects against a typo removing the wrong
     * player's record silently) - if it does not match the stored time, nothing is removed.
     */
    public boolean removeEntry(String mode, UUID playerUuid, String playerName, Double time) {
        if (mode == null || mode.isBlank() || playerName == null || playerName.isBlank()) {
            return false;
        }
        String normalizedMode = normalizeMode(mode);
        List<Entry> entries = readEntries(normalizedMode);
        if (entries.isEmpty()) {
            return false;
        }

        int foundIndex = -1;
        for (int i = 0; i < entries.size(); i++) {
            Entry existing = entries.get(i);
            boolean samePlayer = (playerUuid != null && playerUuid.equals(existing.playerUuid))
                    || (playerUuid == null && existing.playerUuid == null && playerName.equalsIgnoreCase(existing.playerName))
                    || playerName.equalsIgnoreCase(existing.playerName);
            if (!samePlayer) {
                continue;
            }
            if (time != null && Math.abs(existing.score - time) > 0.0005) {
                // Same player, but the time given does not match what is stored - do not remove,
                // since this is very likely a typo rather than an intentional removal.
                continue;
            }
            foundIndex = i;
            break;
        }

        if (foundIndex < 0) {
            return false;
        }

        entries.remove(foundIndex);
        entries.sort(Comparator.comparingDouble(e -> e.score));
        writeEntries(normalizedMode, entries);
        return true;
    }

    /**
     * Manually sets an exact position on a leaderboard, bypassing the normal sorted add/remove
     * flow. Kept for power-user/admin correction use; addEntry/removeEntry are the normal path.
     */
    public boolean setLeaderboardEntry(String mode, int position, UUID playerUuid, String playerName, double score) {
        if (mode == null || mode.isBlank() || position < 1 || position > MAX_POSITIONS) {
            return false;
        }
        String normalizedMode = normalizeMode(mode);
        ensureLeaderboardSection(normalizedMode, mode.trim());
        configuration.set("leaderboards." + normalizedMode + ".positions." + position + ".player", playerName == null ? "" : playerName);
        configuration.set("leaderboards." + normalizedMode + ".positions." + position + ".playerUuid", playerUuid == null ? null : playerUuid.toString());
        configuration.set("leaderboards." + normalizedMode + ".positions." + position + ".score", score);
        save();
        return true;
    }

    /**
     * Renders a mode's leaderboard as display lines, one per position 1..MAX_POSITIONS. This works
     * even for a mode that has never had an entry added - it simply renders every slot as the empty
     * placeholder, so every arena/mode can be listed without a separate "create leaderboard" step.
     */
    public List<String> getLeaderboardLines(String mode) {
        List<String> lines = new ArrayList<>();
        if (mode == null || mode.isBlank()) {
            return lines;
        }
        String normalizedMode = normalizeMode(mode);
        lines.add("§eMode: " + getLeaderboardDisplayName(mode));
        List<Entry> entries = readEntries(normalizedMode);
        for (int position = 1; position <= MAX_POSITIONS; position++) {
            int index = position - 1;
            if (index < entries.size()) {
                Entry entry = entries.get(index);
                // Color the player's name using their LuckPerms rank prefix color, if LuckPerms is
                // installed and they have one configured. Falls back to plain white if not.
                String nameColor = entry.playerUuid != null ? me.skepi.skepifb.util.LuckPermsUtil.getRankColor(entry.playerUuid) : null;
                String coloredName = (nameColor != null ? nameColor : "§f") + entry.playerName;
                lines.add("§7" + position + ". " + coloredName + " §7- §f" + String.format(Locale.ROOT, "%.3f", entry.score));
            } else {
                lines.add("§7" + position + ". §8-.--");
            }
        }
        return lines;
    }

    private String normalizeMode(String mode) {
        return mode == null ? "" : mode.trim().toLowerCase(Locale.ROOT);
    }

    // ------------------------------------------------------------------
    // Position tags: links a specific leaderboard placement (e.g. "3rd on Dune") to a display
    // name, stored under a separate "positionTags" section of this same leaderboard.yml so it
    // lives alongside the leaderboard data it references. Used by the tag shop to figure out which
    // position-based tags a given player currently qualifies for. Equipping a tag applies its
    // display text directly as a LuckPerms prefix (see TagManager) - no LuckPerms group,
    // permission, or parent is involved at all, so this never conflicts with any other parent/group
    // a player already has.
    // ------------------------------------------------------------------

    /**
     * Returns the position (1..MAX_POSITIONS) the given player currently holds on a mode's
     * leaderboard, or -1 if they are not currently on it.
     */
    public int getPlayerPosition(String mode, UUID playerUuid) {
        if (mode == null || mode.isBlank() || playerUuid == null) {
            return -1;
        }
        String normalizedMode = normalizeMode(mode);
        List<Entry> entries = readEntries(normalizedMode);
        for (int i = 0; i < entries.size(); i++) {
            if (playerUuid.equals(entries.get(i).playerUuid)) {
                return i + 1;
            }
        }
        return -1;
    }

    public boolean setPositionTag(String mode, int position, String display) {
        if (mode == null || mode.isBlank() || position < 1 || position > MAX_POSITIONS || display == null || display.isBlank()) {
            return false;
        }
        String normalizedMode = normalizeMode(mode);
        String base = "positionTags." + normalizedMode + "." + position;
        configuration.set(base + ".display", display.trim());
        save();
        return true;
    }

    public boolean removePositionTag(String mode, int position) {
        if (mode == null || mode.isBlank() || position < 1 || position > MAX_POSITIONS) {
            return false;
        }
        String normalizedMode = normalizeMode(mode);
        String base = "positionTags." + normalizedMode + "." + position;
        if (!configuration.isConfigurationSection(base)) {
            return false;
        }
        configuration.set(base, null);
        save();
        return true;
    }

    public String getPositionTagDisplay(String mode, int position) {
        if (mode == null || mode.isBlank() || position < 1 || position > MAX_POSITIONS) {
            return null;
        }
        return configuration.getString("positionTags." + normalizeMode(mode) + "." + position + ".display", null);
    }

    /**
     * Every mode name that has at least one position-tag configured, so callers (the tag shop) only
     * need to check a player's placement on modes that actually matter instead of every arena.
     */
    public Set<String> getModesWithPositionTags() {
        Set<String> modes = new LinkedHashSet<>();
        ConfigurationSection section = configuration.getConfigurationSection("positionTags");
        if (section == null) {
            return modes;
        }
        modes.addAll(section.getKeys(false));
        return modes;
    }

    private void createDefaultPositionTagsSectionIfMissing() {
        if (configuration.isConfigurationSection("positionTags")) {
            return;
        }
        // Nothing to seed anymore - positionTags entries are now auto-generated per mode the first
        // time anyone is added to that mode's leaderboard (see ensurePositionTagsAutoGenerated).
        // This just guarantees the section exists so getModesWithPositionTags() never sees null.
        configuration.createSection("positionTags");
        save();
    }

    private void save() {
        try {
            configuration.save(leaderboardFile);
        } catch (IOException ex) {
            plugin.getLogger().warning("Failed to save leaderboard.yml: " + ex.getMessage());
        }
    }
}
